export const GET_WORKOUTS = 'GET_WORKOUTS';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const ADD_WORKOUT = 'ADD_WORKOUT';

export const GET_ROUTINES = 'GET_ROUTINES';
export const DELETE_ROUTINE = 'DELETE_ROUTINE';
export const ADD_ROUTINE = 'ADD_ROUTINE';

export const GET_EXERCISES = 'GET_EXERCISES';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const ADD_EXERCISE = 'ADD_EXERCISE';

export const GET_ERRORS = 'GET_ERRORS';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
