# Generated by Django 3.1.1 on 2020-10-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(to='exercises.Exercise'),
        ),
    ]
